spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/power_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#    username: test
#    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.101.72.76:3306/community?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: test
    password: test
    hikari:
      pool-name: DateHikari #连接池名称
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 600000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  mail:
    host: smtp.qq.com
    port: 587
    username: 1536079858@qq.com
    password: rcdrbngvazcuhcac
    properties:
      mail.smtp.auth: true

mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.nowcoder.community.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

logging:
  level:
    com.nowcoder.community: debug

















